# Generated by Django 4.0.1 on 2022-01-28 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Avaliation', 'verbose_name_plural': 'Avaliations'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
    ]
